local _, namespace = ...

local L = setmetatable({}, { __index = function(t, k)
	local v = tostring(k)
	rawset(t, k, v)
	return v
end })

namespace.L = L

local LOCALE = GetLocale()

if LOCALE == "enUS" or LOCALE == "enGB" then
	-- No translation needed for english client, so we simply return
	return 
end

if LOCALE == "deDE" then
	-- German translations go here
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "Klingenwirbel"
		L["Adrenaline Rush"] = "Adrenalinrausch"
		L["Preparation"] = "Vorbereitung"
		L["Ghostly Strike"] = "Geisterhafter Stoß"
		L["Premeditation"] = "Konzentration"
		L["Cold Blood"] = "Kaltblütigkeit"
		L["Riposte"] = "Riposte"
		L["Shadowstep"] = "Schattenschritt"
		L["Cheating Death"] = "Von der Schippe springen"

		L["Bestial Wrath"] = "Zorn des Wildtiers"
		L["Intimidation"] = "Einschüchterung"
		L["Deterrence"] = "Abschreckung"
		L["Scatter Shot"] = "Streuschuss"
		L["Aimed Shot"] = "Gezielter Schuss"
		L["Silencing Shot"] = "Unterdrückender Schuss"
		L["Readiness"] = "Bereitschaft"

		L["Last Stand"] = "Letztes Gefecht"
		L["Sweeping Strikes"] = "Weitreichende Stöße"
		L["Death Wish"] = "Todeswunsch"
		L["Concussion Blow"] = "Erschütternder Schlag"

		L["Inner Focus"] = "Innerer Fokus"
		L["Power Infusion"] = "Seele der Macht"
		L["Silence"] = "Stille"
		L["Pain Suppression"] = "Schmerzunterdrückung"
		L["Lightwell"] = "Brunnen des Lichts"

		L["Elemental Mastery"] = "Elementarbeherrschung"
		L["Stormstrike"] = "Sturmschlag"
		L["Nature's Swiftness"] = "Schnelligkeit der Natur"
		L["Shamanistic Rage"] = "Schamanistische Wut"

		L["Fel Domination"] = "Teufelsbeherrschung"
		L["Amplify Curse"] = "Fluch verstärken"
		L["Shadowfury"] = "Schattenfurie"
		L["Backlash"] = "Heimzahlen"

		L["Divine Favor"] = "Göttliche Gunst"
		L["Holy Shock"] = "Heiliger Schock"
		L["Holy Shield"] = "Heiliger Schild"
		L["Repentance"] = "Buße"
		L["Divine Illumination"] = "Göttliche Eingebung"
		L["Avenger's Shield"] = "Schild des Rächers"
		L["Crusader Strike"] = "Kreuzfahrerstoß"

		L["Innervate"] = "Anregen"
		L["Faerie Fire (Feral)"] = "Feenfeuer (Tiergestalt)"
		L["Feral Charge"] = "Wilde Attacke"
		L["Swiftmend"] = "Rasche Heilung"
		L["Force of Nature"] = "Naturgewalt"

		L["Presence of Mind"] = "Geistesgegenwart"
		L["Arcane Power"] = "Arkane Macht"
		L["Combustion"] = "Verbrennung"
		L["Cold Snap"] = "Kälteeinbruch"
		L["Ice Block"] = "Eisblock"
		L["Dragon's Breath"] = "Drachenodem"
		L["Icy Veins"] = "Eisige Adern"
		L["Summon Water Elemental"] = "Wasserelementar beschwören"
		L["Freeze"] = "Eiskälte"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "Wille der Verlassenen"
		L["Perception"] = "Wachsamkeit"
		L["War Stomp"] = "Kriegsdonner"
		L["Stoneform"] = "Steingestalt"
		L["Cannibalize"] = "Kannibalismus"
		L["Blood Fury"] = "Kochendes Blut"
		L["Berserking"] = "Berserker"
		L["Shadowmeld"] = "Schattenhaftigkeit"
		L["Escape Artist"] = "Entfesselungskünstler"
		L["Arcane Torrent"] = "Arkaner Strom"
		L["Mana Tap"] = "Manadurst"
		L["Gift of the Naaru"] = "Gabe der Naaru"

		L["Brittle Armor"] = "Spröde Rüstung"
		L["Unstable Power"] = "Instabile Macht"
		L["Restless Strength"] = "Ruhelose Stärke"
		L["Ephemeral Power"] = "Ephemere Macht"
		L["Massive Destruction"] = "Massive Zerstörung"
		L["Arcane Potency"] = "Arkane Kraft"
		L["Energized Shield"] = "Energiegeladener Schild"
		L["Brilliant Light"] = "Gleißendes Licht"
		L["Mar'li's Brain Boost"] = "Mar'lis fokussierte Gedanken"
		L["Burst of Energy"] = "Energieexplosion"
		L["Refocus"] = "Refokussieren"
		L["Venomous Totem"] = "Gifttotem"
		L["Mind Quickening"] = "Gedankensprung"
		L["Gift of Life"] = "Geschenk des Lebens"
		L["Blinding Light"] = "Blendendes Licht"
		L["Nature Aligned"] = "Naturverbundenheit"
		L["Earthstrike"] = "Erdstoß"
		L["Badge of the Swarmguard"] = "Abzeichen der Schwarmwache"
		L["Speed"] = "Tempo"
		L["Immune Root/Snare/Stun"] = "Immunität gegen Unbeweglichkeit/Verlangsamung/Betäuben"
		L["Immune Fear/Polymorph/Snare"] = "Immunität gegen Furcht/Verwandlung/Verlangsamung"
		L["Immune Charm/Fear/Stun"] = "Immunität Bezauberung/Furcht/Betäuben"
		L["Immune Charm/Fear/Polymorph"] = "Immunität Bezauberung/Furcht/Verwandlung"
		L["Immune Fear/Polymorph/Stun"] = "Immunität Furcht/Verwandlung/Betäuben"
		L["Tidal Charm"] = "Gezeitenglücksbringer"
		L["Diamond Flask"] = "Diamantenfläschchen"
		L["Fearless"] = "Furchtlos"
		L["Net-o-Matic"] = "Net-o-Matik"
		L["The Burrower's Shell"] = "Panzer des Wühlers"
		L["Aura of Protection"] = "Körperlicher Schutz"
		L["The Eye of the Dead"] = "Das Auge des Todes"
		L["Essence of Sapphiron"] = "Essenz Saphirons"
		L["Persistent Shield"] = "Standhafter Schild"
		L["Slayer's Crest"] = "Wappen des Schlächters"
		L["Kiss of the Spider"] = "Kuss der Spinne"
		
		L["PvP Trinket"] = "PvP Schmuck"
		L["Tremendous Fortitude"] = "Gewaltige Seelenstärke"
		L["Talisman of the Horde"] = "Talisman der Horde"
		L["Talisman of the Alliance"] = "Talisman der Allianz"
		
		L["Frost Reflector"] = "Frostreflektor"
		L["Shadow Reflector"] = "Schattenreflektor"
		L["Fire Reflector"] = "Feuerreflektor"
		
		L["Healing Potion"] = "Heiltrank"
		L["Healing Draught"] = "Heilgebräu"
		L["Restore Mana"] = "Mana wiederherstellen"
		L["Free Action"] = "Freie Aktion"
		L["Living Free Action"] = "Lebhafte freie Aktion"
		L["Invulnerability"] = "Unverwundbarkeit"
		L["Restoration"] = "Wiederherstellung"
		L["Restore Energy"] = "Energie wiederherstellen"

		L["Recently Bandaged"] = "Kürzlich bandagiert"
		L["Iron Grenade"] = "Eisengranate"
		L["Thorium Grenade"] = "Thoriumgranate"
		L["Goblin Sapper Charge"] = "Goblinsche Pioniersprengladung"
		L["Flash Bomb"] = "Blitzstrahlbombe"
		L["Arcane Bomb"] = "Arkane Bombe"
		L["Adamantite Grenade"] = "Adamantitgranate"
		L["Super Sapper Charge"] = "Super Pioniersprengladung"
		
		L["Sleep"] = "Schlaf"
		L["Flee"] = "Fliehen"
		L["Gnomish Rocket Boots"] = "Gnomen-Raketenstiefel"
		L["Goblin Rocket Boots"] = "Goblin-Raketenstiefel"
		L["Running Speed"] = "Lauftempo"
		L["Gnomish Mind Control Cap"] = "Gnomen-Gedankenkontrollkappe"
		L["Reckless Charge"] = "Tollkühnes Stürmen"
		L["Rocket Boots Engaged"] = "Raketenstiefel gestartet"

		-- Warrior
		L["Charge"] = "Sturmangriff"
		L["Mocking Blow"] = "Spöttischer Schlag"
		L["Mortal Strike"] = "Tödlicher Stoß"
		L["Overpower"] = "Überwältigen"
		L["Retaliation"] = "Gegenschlag"
		L["Thunder Clap"] = "Donnerknall"
		L["Berserker Rage"] = "Berserkerwut"
		L["Bloodthirst"] = "Blutdurst"
		L["Challenging Shout"] = "Herausforderungsruf"
		L["Intercept"] = "Abfangen"
		L["Intimidating Shout"] = "Drohruf"
		L["Pummel"] = "Zuschlagen"
		L["Recklessness"] = "Tollkühnheit"
		L["Whirlwind"] = "Wirbelwind"
		L["Bloodrage"] = "Blutrausch"
		L["Disarm"] = "Entwaffnen"
		L["Revenge"] = "Rache"
		L["Shield Bash"] = "Schildhieb"
		L["Shield Block"] = "Schildblock"
		L["Shield Slam"] = "Schildschlag"
		L["Shield Wall"] = "Schildwall"
		L["Spell Reflect"] = "Zauberreflexion"
		L["Intervene"] = "Einschreiten"

		-- Paladin
		L["Consecration"] = "Weihe"
		L["Exorcism"] = "Exorzismus"
		L["Hammer of Wrath"] = "Hammer des Zorns"
		L["Holy Wrath"] = "Heiliger Zorn"
		L["Lay on Hands"] = "Handauflegung"
		L["Turn Undead"] = "Untote vertreiben"
		L["Blessing of Freedom"] = "Segen der Freiheit"
		L["Blessing of Protection"] = "Segen des Schutzes"
		L["Divine Intervention"] = "Göttliches Eingreifen"
		L["Divine Protection"] = "Göttlicher Schutz"
		L["Divine Shield"] = "Gottesschild"
		L["Hammer of Justice"] = "Hammer der Gerechtigkeit"
		L["Judgement"] = "Richturteil"
		L["Forbearance"] = "Vorahnung"
		L["Righteous Defense"] = "Rechtschaffene Verteidigung"
		L["Avenging Wrath"] = "Zornige Vergeltung"

		-- Mage
		L["Blink"] = "Blinzeln"
		L["Portal: Darnassus"] = "Portal: Darnassus"
		L["Portal: Ironforge"] = "Portal: Ironforge"
		L["Portal: Orgrimmar"] = "Portal: Orgrimmar"
		L["Portal: Stormwind"] = "Portal: Stormwind"
		L["Portal: Thunder Bluff"] = "Portal: Thunder Bluff"
		L["Portal: Undercity"] = "Portal: Undercity"
		L["Blast Wave"] = "Druckwelle"
		L["Fire Blast"] = "Feuerschlag"
		L["Fire Ward"] = "Feuerzauberschutz"
		L["Cone of Cold"] = "Kältekegel"
		L["Frost Nova"] = "Frostnova"
		L["Frost Ward"] = "Frostzauberschutz"
		L["Ice Barrier"] = "Eisbarriere"
		L["Counterspell"] = "Gegenzauber"
		L["Evocation"] = "Hervorrufung"
		L["Invisibility"] = "Unsichtbarkeit"
		L["Ritual of Refreshment"] = "Tischlein deck dich"

		-- Rogues
		L["Kidney Shot"] = "Nierenhieb"
		L["Evasion"] = "Entrinnen"
		L["Feint"] = "Finte"
		L["Gouge"] = "Solarplexus"
		L["Kick"] = "Tritt"
		L["Sprint"] = "Sprinten"
		L["Blind"] = "Blenden"
		L["Distract"] = "Ablenken"
		L["Stealth"] = "Verstohlenheit"
		L["Vanish"] = "Verschwinden"
		L["Cloak of Shadows"] = "Mantel der Schatten"

		-- Shaman
		L["Reincarnation"] = "Reinkarnation"
		L["Chain Lightning"] = "Kettenblitzschlag"
		L["Earth Shock"] = "Erdschock"
		L["Earthbind Totem"] = "Totem der Erdbindung"
		L["Fire Nova Totem"] = "Totem der Feuernova"
		L["Flame Shock"] = "Flammenschock"
		L["Frost Shock"] = "Frostschock"
		L["Stoneclaw Totem"] = "Totem der Steinklaue"
		L["Astral Recall"] = "Astraler Rückruf"
		L["Grounding Totem"] = "Totem der Erdung"
		L["Mana Tide Totem"] = "Totem der Manaflut"
		L["Bloodlust"] = "Kampfrausch"
		L["Heroism"] = "Heldentum"
		L["Fire Elemental Totem"] = "Totem des Feuerelementars"
		L["Earth Elemental Totem"] = "Totem des Erdelementars"

		-- Hunters
		L["Scare Beast"] = "Wildtier ängstigen"
		L["Tranquilizing Shot"] = "Einlullender Schuss"
		L["Arcane Shot"] = "Arkaner Schuss"
		L["Concussive Shot"] = "Erschütternder Schuss"
		L["Distracting Shot"] = "Ablenkender Schuss"
		L["Flare"] = "Leuchtfeuer"
		L["Multi-Shot"] = "Mehrfachschuss"
		L["Rapid Fire"] = "Schnellfeuer"
		L["Volley"] = "Salve"
		L["Counterattack"] = "Gegenangriff"
		L["Disengage"] = "Rückzug"
		L["Explosive Trap"] = "Sprengfalle"
		L["Feign Death"] = "Totstellen"
		L["Frost Trap"] = "Frostfalle"
		L["Immolation Trap"] = "Feuerbrandfalle"
		L["Mongoose Bite"] = "Mungobiss"
		L["Raptor Strike"] = "Raptorstoß"
		L["Wyvern Sting"] = "Stich des Flügeldrachen"
		L["Misdirection"] = "Irreführung"
		L["Kill Command"] = "Fass!"
		L["Snake Trap"] = "Schlangenfalle"
		L["Thunderstomp"] = "Donnerstampfer"
		L["Warp"] = "Raumkrümmung"
		L["Dive"] = "Sturzflug"

		-- Warlocks
		L["Soulstone Resurrection"] = "Seelenstein-Auferstehung"
		L["Curse of Doom"] = "Fluch der Verdammnis"
		L["Death Coil"] = "Todesmantel"
		L["Howl of Terror"] = "Schreckensgeheul"
		L["Inferno"] = "Inferno"
		L["Ritual of Doom"] = "Ritual der Verdammnis"
		L["Shadow Ward"] = "Schattenzauberschutz"
		L["Conflagrate"] = "Feuersbrunst"
		L["Shadowburn"] = "Schattenbrand"
		L["Soul Fire"] = "Seelenfeuer"
		L["Devour Magic"] = "Magie verschlingen"
		L["Spell Lock"] = "Zaubersperre"
		L["Lash of Pain"] = "Schmerzenspeitsche"
		L["Soothing Kiss"] = "Besänftigender Kuss"
		L["Cleave"] = "Spalten"

		-- Priest
		L["Elune's Grace"] = "Elunes Anmut"
		L["Feedback"] = "Rückkopplung"
		L["Power Word: Shield"] = "Machtwort: Schild"
		L["Desperate Prayer"] = "Verzweifeltes Gebet"
		L["Fear Ward"] = "Furchtzauberschutz"
		L["Devouring Plague"] = "Verschlingende Seuche"
		L["Fade"] = "Verblassen"
		L["Mind Blast"] = "Gedankenschlag"
		L["Psychic Scream"] = "Psychischer Schrei"
		L["Symbol of Hope"] = "Symbol der Hoffnung"
		L["Chastise"] = "Züchtigung"
		L["Prayer of Mending"] = "Gebet der Besserung"
		L["Shadowfiend"] = "Schattengeist"
		L["Shadow Word: Death"] = "Schattenwort: Tod"
		L["Starshards"] = "Sternensplitter"
		L["Consume Magic"] = "Magie verzehren"
		
		-- Druid
		L["Barkskin"] = "Baumrinde"
		L["Faerie Fire"] = "Feenfeuer"
		L["Hurricane"] = "Hurrikan"
		L["Nature's Grasp"] = "Griff der Natur"
		L["Bash"] = "Hieb"
		L["Challenging Roar"] = "Herausforderndes Gebrüll"
		L["Cower"] = "Ducken"
		L["Dash"] = "Spurt"
		L["Enrage"] = "Wutanfall"
		L["Frenzied Regeneration"] = "Rasende Regeneration"
		L["Prowl"] = "Schleichen"
		L["Tiger's Fury"] = "Tigerfuror"
		L["Rebirth"] = "Wiedergeburt"
		L["Tranquility"] = "Gelassenheit"
		
return end

if LOCALE == "frFR" then
	-- French translations go here
	-- Thanks to Oropopzz for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "Déluge de lames"
		L["Adrenaline Rush"] = "Poussée d'adrénaline"
		L["Preparation"] = "Préparation"
		L["Ghostly Strike"] = "Frappe fantomatique"
		L["Premeditation"] = "Préméditation"
		L["Cold Blood"] = "Sang froid"
		L["Riposte"] = "Riposte"
		L["Shadowstep"] = "Pas de l'ombre"
		L["Cheating Death"] = "Trompe-la-mort"

		L["Bestial Wrath"] = "Courroux bestial"
		L["Intimidation"] = "Intimidation"
		L["Deterrence"] = "Dissuasion"
		L["Scatter Shot"] = "Flèche de dispersion"
		L["Aimed Shot"] = "Visée"
		L["Silencing Shot"] = "Flèche-bâillon"
		L["Readiness"] = "Promptitude"

		L["Last Stand"] = "Dernier rempart"
		L["Sweeping Strikes"] = "Attaques circulaires"
		L["Death Wish"] = "Souhait mortel"
		L["Concussion Blow"] = "Bourrasque"

		L["Inner Focus"] = "Focalisation améliorée"
		L["Power Infusion"] = "Infusion de puissance"
		L["Silence"] = "Silence"
		L["Pain Suppression"] = "Suppression de la douleur"
		L["Lightwell"] = "Puits de lumière"

		L["Elemental Mastery"] = "Maîtrise élémentaire"
		L["Stormstrike"] = "Courroux naturel"
		L["Nature's Swiftness"] = "Rapidité de la nature"
		L["Shamanistic Rage"] = "Rage libérée"

		L["Fel Domination"] = "Domination corrompue"
		L["Amplify Curse"] = "Malédiction amplifiée"
		L["Shadowfury"] = "Furie de l'ombre"
		L["Backlash"] = "Contrecoup"

		L["Divine Favor"] = "Faveur divine"
		L["Holy Shock"] = "Horion sacré"
		L["Holy Shield"] = "Bouclier sacré"
		L["Repentance"] = "Repentir"
		L["Divine Illumination"] = "Illumination divine"
		L["Avenger's Shield"] = "Bouclier du vengeur"
		L["Crusader Strike"] = "Frappe du croisé"

		L["Innervate"] = "Innervation"
		L["Faerie Fire (Feral)"] = "Lucioles (farouche)"
		L["Feral Charge"] = "Lucioles (farouche)"
		L["Swiftmend"] = "Prompte guérison"
		L["Force of Nature"] = "Force de la nature"

		L["Presence of Mind"] = "Présence spirituelle"
		L["Arcane Power"] = "Pouvoir des arcanes"
		L["Combustion"] = "Combustion"
		L["Cold Snap"] = "Morsure de froid"
		L["Ice Block"] = "Bloc de glace"
		L["Dragon's Breath"] = "Souffle du dragon"
		L["Icy Veins"] = "Veines glaciales"
		L["Summon Water Elemental"] = "Invocation d'un élémentaire d'eau"
		L["Freeze"] = "Gel"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "Volonté des Réprouvés"
		L["Perception"] = "Perception"
		L["War Stomp"] = "Choc martial"
		L["Stoneform"] = "Forme de pierre"
		L["Cannibalize"] = "Cannibalisme"
		L["Blood Fury"] = "Fureur sanguinaire"
		L["Berserking"] = "Berserker"
		L["Shadowmeld"] = "Camouflage dans l'ombre"
		L["Escape Artist"] = "Maître de l'évasion"
		L["Arcane Torrent"] = "Torrent arcanique"
		L["Mana Tap"] = "Ponction de mana"
		L["Gift of the Naaru"] = "Don des naaru"

		L["Brittle Armor"] = "Armure fragile"
		L["Unstable Power"] = "Puissance instable"
		L["Restless Strength"] = "Force inconstante"
		L["Ephemeral Power"] = "Puissance éphémère"
		L["Massive Destruction"] = "Destruction massive"
		L["Arcane Potency"] = "Toute-puissance des arcanes"
		L["Energized Shield"] = "Bouclier dynamisé"
		L["Brilliant Light"] = "Lumière éclatante"
		L["Mar'li's Brain Boost"] = "Accélération mentale de Mar'li"
		L["Burst of Energy"] = "Explosion d'énergie"
		L["Refocus"] = "Refocalisation"
		L["Venomous Totem"] = "Totem venimeux"
		L["Mind Quickening"] = "Vivacité d'esprit"
		L["Gift of Life"] = "Don de vie"
		L["Blinding Light"] = "Lumière aveuglante"
		L["Nature Aligned"] = "Alignement sur la nature"
		L["Earthstrike"] = "Choc de terre"
		L["Badge of the Swarmguard"] = "Insigne de garde-essaim"
		L["Speed"] = "Vitesse"
		L["Immune Root/Snare/Stun"] = "Immunité : Immobiliser/Ralentir/Etourdir"
		L["Immune Fear/Polymorph/Snare"] = "Immunité : Peur/Métamorphose/Ralentir"
		L["Immune Charm/Fear/Stun"] = "Immunité : Charme/Peur/Etourdir"
		L["Immune Charm/Fear/Polymorph"] = "Immunité : Charme/Peur/Métamorphose"
		L["Immune Fear/Polymorph/Stun"] = "Immunité : Peur/Métamorphose/Etourdir"
		L["Tidal Charm"] = "Charme des flots"
		L["Diamond Flask"] = "Flacon de diamant"
		L["Fearless"] = "Intrépide"
		L["Net-o-Matic"] = "Lance-filet automatique"
		L["The Burrower's Shell"] = "La Carapace du fouisseur"
		L["Aura of Protection"] = "Aura de protection"
		L["The Eye of the Dead"] = "L'Oeil du mort"
		L["Essence of Sapphiron"] = "Essence de Saphiron"
		L["Persistent Shield"] = "Bouclier persistant"
		L["Slayer's Crest"] = "Blason de tueur"
		L["Kiss of the Spider"] = "Baiser de l'araignée" 
		
		L["PvP Trinket"] = "Bijou JcJ"
		L["Tremendous Fortitude"] = "Robustesse époustouflante"
		L["Talisman of the Horde"] = "Talisman de la Horde"
		L["Talisman of the Alliance"] = "Talisman de l'Alliance"

		L["Frost Reflector"] = "Réflectogivre"
		L["Shadow Reflector"] = "Réflectombre"
		L["Fire Reflector"] = "Réflectofeu"
		
		L["Healing Potion"] = "Potion de soins"
		L["Healing Draught"] = "Breuvage de soin"
		L["Restore Mana"] = "Restauration du mana"
		L["Free Action"] = "Libre action"
		L["Living Free Action"] = "Libre action ravivée"
		L["Invulnerability"] = "Invulnérabilité"
		L["Restoration"] = "Restauration"
		L["Restore Energy"] = "Restauration d'énergie"


		L["Recently Bandaged"] = "Un bandage a été appliqué récemment"
		L["Iron Grenade"] = "Grenade en fer"
		L["Thorium Grenade"] = "Grenade en thorium"
		L["Goblin Sapper Charge"] = "Charge de sapeur gobelin"
		L["Flash Bomb"] = "Bombe éclairante"
		L["Arcane Bomb"] = "Bombe des arcanes"
		L["Adamantite Grenade"] = "Grenade en adamantite"
		L["Super Sapper Charge"] = "Super-charge de sapeur"
		
		L["Sleep"] = "Sommeil"
		L["Flee"] = "Fuir"
		L["Gnomish Rocket Boots"] = "Bottes-fusées gnomes"
		L["Goblin Rocket Boots"] = "Bottes-fusées gobelines"
		L["Running Speed"] = "Vitesse de course"
		L["Gnomish Mind Control Cap"] = "Coiffe de contrôle mental gnome"
		L["Reckless Charge"] = "Charge furieuse"
		L["Rocket Boots Engaged"] = "Bottes-fusées activées"

		-- Warrior
		L["Charge"] = "Charge"
		L["Mocking Blow"] = "Coup railleur"
		L["Mortal Strike"] = "Frappe mortelle"
		L["Overpower"] = "Fulgurance"
		L["Retaliation"] = "Représailles"
		L["Thunder Clap"] = "Coup de tonnerre"
		L["Berserker Rage"] = "Rage berserker"
		L["Bloodthirst"] = "Sanguinaire"
		L["Challenging Shout"] = "Cri de défi"
		L["Intercept"] = "Interception"
		L["Intimidating Shout"] = "Cri d'intimidation"
		L["Pummel"] = "Volée de coups"
		L["Recklessness"] = "Témérité"
		L["Whirlwind"] = "Tourbillon"
		L["Bloodrage"] = "Rage sanguinaire"
		L["Disarm"] = "Désarmement"
		L["Revenge"] = "Vengeance"
		L["Shield Bash"] = "Coup de bouclier"
		L["Shield Block"] = "Maîtrise du blocage"
		L["Shield Slam"] = "Heurt de bouclier"
		L["Shield Wall"] = "Mur protecteur"
		L["Spell Reflect"] = "Renvoi de sort"
		L["Intervene"] = "Intervention"

		-- Paladin
		L["Consecration"] = "Consécration"
		L["Exorcism"] = "Exorcisme"
		L["Hammer of Wrath"] = "Marteau de courroux"
		L["Holy Wrath"] = "Colère divine"
		L["Lay on Hands"] = "Imposition des mains"
		L["Turn Undead"] = "Renvoi des morts-vivants"
		L["Blessing of Freedom"] = "Bénédiction de liberté"
		L["Blessing of Protection"] = "Bénédiction de protection"
		L["Divine Intervention"] = "Intervention divine"
		L["Divine Protection"] = "Protection divine"
		L["Divine Shield"] = "Bouclier divin"
		L["Hammer of Justice"] = "Marteau de la justice"
		L["Judgement"] = "Jugement"
		L["Forbearance"] = "Longanimité"
		L["Righteous Defense"] = "Défense vertueuse"
		L["Avenging Wrath"] = "Courroux vengeur"

		-- Mage
		L["Blink"] = "Transfert"
		L["Portal: Darnassus"] = "Portail: Darnassus"
		L["Portal: Ironforge"] = "Portail: Ironforge"
		L["Portal: Orgrimmar"] = "Portail: Orgrimmar"
		L["Portal: Stormwind"] = "Portail: Stormwind"
		L["Portal: Thunder Bluff"] = "Portail: Thunder Bluff"
		L["Portal: Undercity"] = "Portail: Undercity"
		L["Blast Wave"] = "Vague explosive"
		L["Fire Blast"] = "Trait de feu"
		L["Fire Ward"] = "Gardien de feu"
		L["Cone of Cold"] = "Cône de froid"
		L["Frost Nova"] = "Nova de givre"
		L["Frost Ward"] = "Gardien de givre"
		L["Ice Barrier"] = "Barrière de glace"
		L["Counterspell"] = "Contresort"
		L["Evocation"] = "Evocation"
		L["Invisibility"] = "Invisibilité"
		L["Ritual of Refreshment"] = "Rituel des rafraîchissements"

		-- Rogues
		L["Kidney Shot"] = "Aiguillon perfide"
		L["Evasion"] = "Evasion"
		L["Feint"] = "Feinte"
		L["Gouge"] = "Suriner"
		L["Kick"] = "Coup de pied"
		L["Sprint"] = "Sprint"
		L["Blind"] = "Cécité"
		L["Distract"] = "Distraction"
		L["Stealth"] = "Camouflage"
		L["Vanish"] = "Disparition"
		L["Cloak of Shadows"] = "Cape d'ombre"

		-- Shaman
		L["Reincarnation"] = "Réincarnation"
		L["Chain Lightning"] = "Chaîne d'éclairs"
		L["Earth Shock"] = "Horion de terre"
		L["Earthbind Totem"] = "Totem de lien terrestre"
		L["Fire Nova Totem"] = "Totem Nova de feu"
		L["Flame Shock"] = "Horion de flammes"
		L["Frost Shock"] = "Horion de givre"
		L["Stoneclaw Totem"] = "Totem de Griffes de pierre"
		L["Astral Recall"] = "Rappel astral"
		L["Grounding Totem"] = "Totem de Glèbe"
		L["Mana Tide Totem"] = "Totem de Vague de mana"
		L["Bloodlust"] = "Furie sanguinaire"
		L["Heroism"] = "Héroïsme"
		L["Fire Elemental Totem"] = "Totem d'élémentaire de feu"
		L["Earth Elemental Totem"] = "Totem d'élémentaire de terre"

		-- Hunters
		L["Scare Beast"] = "Effrayer une bête"
		L["Tranquilizing Shot"] = "Tir tranquillisant"
		L["Arcane Shot"] = "Tir des arcanes"
		L["Concussive Shot"] = "Trait de choc"
		L["Distracting Shot"] = "Trait provocateur"
		L["Flare"] = "Fusée éclairante"
		L["Multi-Shot"] = "Flèches multiples"
		L["Rapid Fire"] = "Tir rapide"
		L["Volley"] = "Salve"
		L["Counterattack"] = "Contre-attaque"
		L["Disengage"] = "Désengagement"
		L["Explosive Trap"] = "Piège explosif"
		L["Feign Death"] = "Feindre la mort"
		L["Frost Trap"] = "Piège de givre"
		L["Immolation Trap"] = "Piège d'immolation"
		L["Mongoose Bite"] = "Morsure de la mangouste"
		L["Raptor Strike"] = "Attaque du raptor"
		L["Wyvern Sting"] = "Piqûre de wyverne"
		L["Misdirection"] = "Détournement"
		L["Kill Command"] = "Ordre de tuer"
		L["Snake Trap"] = "Piège à serpent"
		L["Thunderstomp"] = "Grondeterre"
		L["Warp"] = "Distorsion"
		L["Dive"] = "Plongeon"

		-- Warlocks
		L["Soulstone Resurrection"] = "Résurrection de Pierre d'âme"
		L["Curse of Doom"] = "Malédiction funeste"
		L["Death Coil"] = "Voile mortel"
		L["Howl of Terror"] = "Hurlement de terreur"
		L["Inferno"] = "Inferno"
		L["Ritual of Doom"] = "Rituel funeste"
		L["Shadow Ward"] = "Gardien de l'ombre"
		L["Conflagrate"] = "Conflagration"
		L["Shadowburn"] = "Brûlure de l'ombre"
		L["Soul Fire"] = "Feu de l'âme"
		L["Devour Magic"] = "Dévorer la magie"
		L["Spell Lock"] = "Verrou magique"
		L["Lash of Pain"] = "Fouet de la douleur"
		L["Soothing Kiss"] = "Baiser apaisant"
		L["Cleave"] = "Enchaînement"

		-- Priest
		L["Elune's Grace"] = "Grâce d'Elune"
		L["Feedback"] = "Réaction"
		L["Power Word: Shield"] = "Mot de pouvoir : Bouclier"
		L["Desperate Prayer"] = "Prière du désespoir"
		L["Fear Ward"] = "Gardien de peur"
		L["Devouring Plague"] = "Peste dévorante"
		L["Fade"] = "Oubli"
		L["Mind Blast"] = "Attaque mentale"
		L["Psychic Scream"] = "Cri psychique"
		L["Symbol of Hope"] = "Symbole d'espoir"
		L["Chastise"] = "Châtier"
		L["Prayer of Mending"] = "Prière de guérison"
		L["Shadowfiend"] = "Ombrefiel"
		L["Shadow Word: Death"] = "Mot de l'ombre : Mort"
		L["Starshards"] = "Eclats stellaires"
		L["Consume Magic"] = "Consumer la magie"
		
		-- Druid
		L["Barkskin"] = "Ecorce"
		L["Faerie Fire"] = "Lucioles"
		L["Hurricane"] = "Ouragan"
		L["Nature's Grasp"] = "Emprise de la nature"
		L["Bash"] = "Sonner"
		L["Challenging Roar"] = "Rugissement provocateur"
		L["Cower"] = "Dérobade"
		L["Dash"] = "Célérité"
		L["Enrage"] = "Enrager"
		L["Frenzied Regeneration"] = "Régénération frénétique"
		L["Prowl"] = "Rôder"
		L["Tiger's Fury"] = "Fureur du tigre"
		L["Rebirth"] = "Renaissance"
		L["Tranquility"] = "Tranquillité"
		
return end

if LOCALE == "esES" or LOCALE == "esMX" then
	-- Spanish translations go here
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""
		L["Riposte"] = ""
		L["Shadowstep"] = ""
		L["Cheating Death"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""
		L["Silencing Shot"] = ""
		L["Readiness"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""
		L["Pain Suppression"] = ""
		L["Lightwell"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""
		L["Shamanistic Rage"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""
		L["Shadowfury"] = ""
		L["Backlash"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""
		L["Divine Illumination"] = ""
		L["Avenger's Shield"] = ""
		L["Crusader Strike"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""
		L["Force of Nature"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""
		L["Dragon's Breath"] = ""
		L["Icy Veins"] = ""
		L["Summon Water Elemental"] = ""
		L["Freeze"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""
		L["Arcane Torrent"] = ""
		L["Mana Tap"] = ""
		L["Gift of the Naaru"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["PvP Trinket"] = ""
		L["Tremendous Fortitude"] = ""
		L["Talisman of the Horde"] = ""
		L["Talisman of the Alliance"] = ""

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""


		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		L["Adamantite Grenade"] = ""
		L["Super Sapper Charge"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""
		L["Rocket Boots Engaged"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""
		L["Spell Reflect"] = ""
		L["Intervene"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""
		L["Righteous Defense"] = ""
		L["Avenging Wrath"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""
		L["Invisibility"] = ""
		L["Ritual of Refreshment"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""
		L["Cloak of Shadows"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""
		L["Bloodlust"] = ""
		L["Heroism"] = ""
		L["Fire Elemental Totem"] = ""
		L["Earth Elemental Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""
		L["Misdirection"] = ""
		L["Kill Command"] = ""
		L["Snake Trap"] = ""
		L["Thunderstomp"] = ""
		L["Warp"] = ""
		L["Dive"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""
		L["Cleave"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		L["Symbol of Hope"] = ""
		L["Chastise"] = ""
		L["Prayer of Mending"] = ""
		L["Shadowfiend"] = ""
		L["Shadow Word: Death"] = ""
		L["Starshards"] = ""
		L["Consume Magic"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end

if LOCALE == "ptBR" then
	-- Brazilian Portuguese translations go here
	-- Note that the EU Portuguese WoW client also
	-- uses the Brazilian Portuguese locale code.
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""
		L["Riposte"] = ""
		L["Shadowstep"] = ""
		L["Cheating Death"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""
		L["Silencing Shot"] = ""
		L["Readiness"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""
		L["Pain Suppression"] = ""
		L["Lightwell"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""
		L["Shamanistic Rage"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""
		L["Shadowfury"] = ""
		L["Backlash"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""
		L["Divine Illumination"] = ""
		L["Avenger's Shield"] = ""
		L["Crusader Strike"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""
		L["Force of Nature"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""
		L["Dragon's Breath"] = ""
		L["Icy Veins"] = ""
		L["Summon Water Elemental"] = ""
		L["Freeze"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""
		L["Arcane Torrent"] = ""
		L["Mana Tap"] = ""
		L["Gift of the Naaru"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["PvP Trinket"] = ""
		L["Tremendous Fortitude"] = ""
		L["Talisman of the Horde"] = ""
		L["Talisman of the Alliance"] = ""

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""


		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		L["Adamantite Grenade"] = ""
		L["Super Sapper Charge"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""
		L["Rocket Boots Engaged"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""
		L["Spell Reflect"] = ""
		L["Intervene"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""
		L["Righteous Defense"] = ""
		L["Avenging Wrath"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""
		L["Invisibility"] = ""
		L["Ritual of Refreshment"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""
		L["Cloak of Shadows"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""
		L["Bloodlust"] = ""
		L["Heroism"] = ""
		L["Fire Elemental Totem"] = ""
		L["Earth Elemental Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""
		L["Misdirection"] = ""
		L["Kill Command"] = ""
		L["Snake Trap"] = ""
		L["Thunderstomp"] = ""
		L["Warp"] = ""
		L["Dive"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""
		L["Cleave"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		L["Symbol of Hope"] = ""
		L["Chastise"] = ""
		L["Prayer of Mending"] = ""
		L["Shadowfiend"] = ""
		L["Shadow Word: Death"] = ""
		L["Starshards"] = ""
		L["Consume Magic"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end

if LOCALE == "ruRU" then
	-- Russian translations go here
	-- Thanks to Мрмоу for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "Шквал клинков"
		L["Adrenaline Rush"] = "Выброс адренлина"
		L["Preparation"] = "Подготовка"
		L["Ghostly Strike"] = "Призрачный удар"
		L["Premeditation"] = "Умысел"
		L["Cold Blood"] = "Хладнокровие"
		L["Riposte"] = ""
		L["Shadowstep"] = ""
		L["Cheating Death"] = ""

		L["Bestial Wrath"] = "Звериный гнев"
		L["Intimidation"] = "Устрашение"
		L["Deterrence"] = "Сдерживание"
		L["Scatter Shot"] = "Дезориентирующий выстрел"
		L["Aimed Shot"] = "Прицельный выстрел"
		L["Silencing Shot"] = ""
		L["Readiness"] = ""

		L["Last Stand"] = "Ни шагу назад"
		L["Sweeping Strikes"] = "Размашистые удары"
		L["Death Wish"] = "Инстинкт смерти"
		L["Concussion Blow"] = "Оглушающий удар"

		L["Inner Focus"] = "Внутреннее сосредоточение"
		L["Power Infusion"] = "Придание сил"
		L["Silence"] = "Молчание"
		L["Pain Suppression"] = ""
		L["Lightwell"] = ""

		L["Elemental Mastery"] = "Покорение стихий"
		L["Stormstrike"] = "Удар бури"
		L["Nature's Swiftness"] = "Природная стремительность"
		L["Shamanistic Rage"] = ""

		L["Fel Domination"] = "Господство Скверны"
		L["Amplify Curse"] = "Усиление проклятия"
		L["Shadowfury"] = ""
		L["Backlash"] = ""

		L["Divine Favor"] = "Божественное одобрение"
		L["Holy Shock"] = "Шок небес"
		L["Holy Shield"] = "Щит небес"
		L["Repentance"] = "Покаяние"
		L["Divine Illumination"] = ""
		L["Avenger's Shield"] = ""
		L["Crusader Strike"] = ""

		L["Innervate"] = "Озарение"
		L["Faerie Fire (Feral)"] = "Волшебный огонь (сила зверя)"
		L["Feral Charge"] = "Звериная атака"
		L["Swiftmend"] = "Быстрое восстановление"
		L["Force of Nature"] = ""

		L["Presence of Mind"] = "Присутствие разума"
		L["Arcane Power"] = "Мощь тайной магии"
		L["Combustion"] = "Возгорание"
		L["Cold Snap"] = "Холодная хватка"
		L["Ice Block"] = "Ледяная глыба"
		L["Dragon's Breath"] = ""
		L["Icy Veins"] = ""
		L["Summon Water Elemental"] = ""
		L["Freeze"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "Воля Отрекшихся"
		L["Perception"] = "Внимательность"
		L["War Stomp"] = "Громовая поступь"
		L["Stoneform"] = "Каменная форма"
		L["Cannibalize"] = "Каннибализм"
		L["Blood Fury"] = "Кровавое неистовство"
		L["Berserking"] = "Боевое исступление"
		L["Shadowmeld"] = "Слиться с тенью"
		L["Escape Artist"] = "Мастер побега"
		L["Arcane Torrent"] = ""
		L["Mana Tap"] = ""
		L["Gift of the Naaru"] = ""

		L["Brittle Armor"] = "Хрупкие доспехи"
		L["Unstable Power"] = "Изменчивая сила"
		L["Restless Strength"] = "Неодолимая сила"
		L["Ephemeral Power"] = "Эфимерная власть"
		L["Massive Destruction"] = "Массовое разрушение"
		L["Arcane Potency"] = "Чародейское могущество"
		L["Energized Shield"] = "Энергетический щит"
		L["Brilliant Light"] = "Бриллиантовый свет"
		L["Mar'li's Brain Boost"] = "Стимулятор мозга Марли"
		--L["Burst of Energy"] = "Прилив сил" -- Shares the same name with mage evocation
		L["Refocus"] = "Восстановление способностей"
		L["Venomous Totem"] = "Ядовитый тотем"
		L["Mind Quickening"] = "Скорость мысли"
		L["Gift of Life"] = "Дар жизни"
		L["Blinding Light"] = "Слепящий свет"
		L["Nature Aligned"] = "Упорядочение Природы"
		L["Earthstrike"] = "Земной удар"
		L["Badge of the Swarmguard"] = "Жетон Стража Роя"
		L["Speed"] = "Скорость"
		L["Immune Root/Snare/Stun"] = "Неуязвимость к обездвиживанию/ловушкам/оглушению"
		L["Immune Fear/Polymorph/Snare"] = "Неуязвимость к страху/превращению/сковывания"
		L["Immune Charm/Fear/Stun"] = "Неуязвимость к подчинению/страху/оглушению"
		L["Immune Charm/Fear/Polymorph"] = "Неуязвимость к подчинению/страху/превращению"
		L["Immune Fear/Polymorph/Stun"] = "Неуязвимость к страху/превращению/оглушению"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["PvP Trinket"] = ""
		L["Tremendous Fortitude"] = ""
		L["Talisman of the Horde"] = ""
		L["Talisman of the Alliance"] = ""

		L["Frost Reflector"] = "Зеркало Льда"
		L["Shadow Reflector"] = "Отражатель тьмы"
		L["Fire Reflector"] = "Отражатель пламени"
		
		L["Healing Potion"] = "Лечебное зелье"
		L["Healing Draught"] = "Исцеляющее зелье"
		L["Restore Mana"] = "Восполнение маны"
		L["Free Action"] = "Свобода действий"
		L["Living Free Action"] = "Живая свобода действий"
		L["Invulnerability"] = "Неуязвимость"
		--L["Restoration"] = "Восстановление" -- Share same name with druid regrowth
		L["Restore Energy"] = "Восполнение энергии"


		L["Recently Bandaged"] = "Недавняя перевязка"
		L["Iron Grenade"] = "Железная граната"
		L["Thorium Grenade"] = "Ториевая граната"
		L["Goblin Sapper Charge"] = "Гоблинский саперный заряд"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		L["Adamantite Grenade"] = ""
		L["Super Sapper Charge"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "Бегство"
		L["Gnomish Rocket Boots"] = "Гномьи реактивные сапоги"
		L["Goblin Rocket Boots"] = "Гоблинские реактивные сапоги"
		L["Running Speed"] = "Скорость бега"
		L["Gnomish Mind Control Cap"] = "Гномья шапка контроля над разумом"
		L["Reckless Charge"] = "Безрассудная атака"
		L["Rocket Boots Engaged"] = ""

		-- Warrior
		L["Charge"] = "Рывок"
		L["Mocking Blow"] = "Дразнящий удар"
		L["Mortal Strike"] = "Смертельный удар"
		L["Overpower"] = "Превосходство"
		L["Retaliation"] = "Возмездие"
		L["Thunder Clap"] = "Удар грома"
		L["Berserker Rage"] = "Ярость берсерка"
		L["Bloodthirst"] = "Кровожадность"
		L["Challenging Shout"] = "Вызывающий крик"
		L["Intercept"] = "Перехват"
		L["Intimidating Shout"] = "Устрашающий крик"
		L["Pummel"] = "Зуботычина"
		L["Recklessness"] = "Безрассудство"
		L["Whirlwind"] = "Вихрь"
		L["Bloodrage"] = "Кровавая ярость"
		L["Disarm"] = "Разоружение"
		L["Revenge"] = "Реванш"
		L["Shield Bash"] = "Удар щитом"
		L["Shield Block"] = "Блок щитом"
		L["Shield Slam"] = "Скорушение щитом"
		L["Shield Wall"] = "Глухая оборона"
		L["Spell Reflect"] = ""
		L["Intervene"] = ""

		-- Paladin
		L["Consecration"] = "Освящение"
		L["Exorcism"] = "Экзорцизм"
		L["Hammer of Wrath"] = "Молот гнева"
		L["Holy Wrath"] = "Гнев небес"
		L["Lay on Hands"] = "Возложение рук"
		L["Turn Undead"] = "Изгнание нежити"
		L["Blessing of Freedom"] = "Благословение cвободы"
		L["Blessing of Protection"] = "Благословение защиты"
		L["Divine Intervention"] = "Божественное вмешательство"
		L["Divine Protection"] = "Божественная защита"
		L["Divine Shield"] = "Божественный щит"
		L["Hammer of Justice"] = "Молот правосудия"
		L["Judgement"] = "Правосудие"
		L["Forbearance"] = "Воздержанность"
		L["Righteous Defense"] = ""
		L["Avenging Wrath"] = ""

		-- Mage
		L["Blink"] = "Скачок"
		L["Portal: Darnassus"] = "Портал в Дарнасс"
		L["Portal: Ironforge"] = "Портал в Стальгорн"
		L["Portal: Orgrimmar"] = "Портал в Оргриммар"
		L["Portal: Stormwind"] = "Портал в Штормград"
		L["Portal: Thunder Bluff"] = "Портал в Громовой Утес"
		L["Portal: Undercity"] = "Портал в Подгород"
		L["Blast Wave"] = "Взрывная волна"
		L["Fire Blast"] = "Огненный взрыв"
		L["Fire Ward"] = "Защита от огня"
		L["Cone of Cold"] = "Конус холода"
		L["Frost Nova"] = "Кольцо льда"
		L["Frost Ward"] = "Защита от магии льда"
		L["Ice Barrier"] = "Ледяная преграда"
		L["Counterspell"] = "Антимагия"
		L["Evocation"] = "Прилив сил"
		L["Invisibility"] = ""
		L["Ritual of Refreshment"] = ""

		-- Rogues
		L["Kidney Shot"] = "Удар по почкам"
		L["Evasion"] = "Ускользание"
		L["Feint"] = "Ложный выпад"
		L["Gouge"] = "Парализующий удар"
		L["Kick"] = "Пинок"
		L["Sprint"] = "Спринт"
		L["Blind"] = "Ослепление"
		L["Distract"] = "Отвлечение"
		L["Stealth"] = "Незаметность"
		L["Vanish"] = "Исчезновение"
		L["Cloak of Shadows"] = ""

		-- Shaman
		L["Reincarnation"] = "Восстание из мертвых"
		L["Chain Lightning"] = "Цепная молния"
		L["Earth Shock"] = "Земной шок"
		L["Earthbind Totem"] = "Тотем оков земли"
		L["Fire Nova Totem"] = "Тотем кольца огня"
		L["Flame Shock"] = "Огненный шок"
		L["Frost Shock"] = "Ледяной шок"
		L["Stoneclaw Totem"] = "Тотем каменного когтя"
		L["Astral Recall"] = "Астральное возвращение"
		L["Grounding Totem"] = "Тотем заземления"
		L["Mana Tide Totem"] = "Тотем прилива маны"
		L["Bloodlust"] = ""
		L["Heroism"] = ""
		L["Fire Elemental Totem"] = ""
		L["Earth Elemental Totem"] = ""

		-- Hunters
		L["Scare Beast"] = "Отпугивание зверя"
		L["Tranquilizing Shot"] = "Усмиряющий выстрел"
		L["Arcane Shot"] = "Чародейский выстрел"
		L["Concussive Shot"] = "Шокирующий выстрел"
		L["Distracting Shot"] = "Отвлекающий выстрел"
		L["Flare"] = "Осветительная ракета"
		L["Multi-Shot"] = "Залп"
		L["Rapid Fire"] = "Быстрая стрельба"
		L["Volley"] = "Град стрел"
		L["Counterattack"] = "Контратака"
		L["Disengage"] = "Отрыв"
		L["Explosive Trap"] = "Взрывная ловушка"
		L["Feign Death"] = "Притвориться мертвым"
		L["Frost Trap"] = "Ледяная ловушка"
		L["Immolation Trap"] = "Обжигающая ловушка"
		L["Mongoose Bite"] = "Укус мангуста"
		L["Raptor Strike"] = "Удар ящера"
		L["Wyvern Sting"] = "Жало виверны"
		L["Misdirection"] = ""
		L["Kill Command"] = ""
		L["Snake Trap"] = ""
		L["Thunderstomp"] = ""
		L["Warp"] = ""
		L["Dive"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = "Воскрешение камнем души"
		L["Curse of Doom"] = "Проклятие рока"
		L["Death Coil"] = "Лик смерти"
		L["Howl of Terror"] = "Вой ужаса"
		L["Inferno"] = "Инфернал"
		L["Ritual of Doom"] = "Ритуал Рока"
		L["Shadow Ward"] = "Защита от темной магии"
		L["Conflagrate"] = "Поджигание"
		L["Shadowburn"] = "Ожог тьмы"
		L["Soul Fire"] = "Ожог души"
		L["Devour Magic"] = "Пожирание магии"
		L["Spell Lock"] = "Запрет чар"
		L["Lash of Pain"] = "Всплеск боли"
		L["Soothing Kiss"] = "Утешительный поцелуй"
		L["Cleave"] = ""

		-- Priest
		L["Elune's Grace"] = "Благодать Элуны"
		L["Feedback"] = "Ответная реакция"
		L["Power Word: Shield"] = "Слово силы: Щит"
		L["Desperate Prayer"] = "Молитва отчаяния"
		L["Fear Ward"] = "Защита от страха"
		L["Devouring Plague"] = "Всепожирающая чума"
		L["Fade"] = "Уход в тень"
		L["Mind Blast"] = "Взрыв разума"
		L["Psychic Scream"] = "Ментальный крик"
		L["Symbol of Hope"] = ""
		L["Chastise"] = ""
		L["Prayer of Mending"] = ""
		L["Shadowfiend"] = ""
		L["Shadow Word: Death"] = ""
		L["Starshards"] = ""
		L["Consume Magic"] = ""
		
		-- Druid
		L["Barkskin"] = "Дубовая кожа"
		L["Faerie Fire"] = "Волшебный огонь"
		L["Hurricane"] = "Гроза"
		L["Nature's Grasp"] = "Природный захват"
		L["Bash"] = "Оглушить"
		L["Challenging Roar"] = "Вызывающий рев"
		L["Cower"] = "Попятиться"
		L["Dash"] = "Порыв"
		L["Enrage"] = "Исступление"
		L["Frenzied Regeneration"] = "Неистовое восстановление"
		L["Prowl"] = "Крадущийся зверь"
		L["Tiger's Fury"] = "Тигриное неистовство"
		L["Rebirth"] = "Возрождение"
		L["Tranquility"] = "Спокойствие"
		
return end

if LOCALE == "koKR" then
	-- Korean translations go here
	-- Thanks to 좌상탄 for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "폭풍의 칼날"
		L["Adrenaline Rush"] = "아드레날린 촉진"
		L["Preparation"] = "마음가짐"
		L["Ghostly Strike"] = "그림자 일격"
		L["Premeditation"] = "사전계획"
		L["Cold Blood"] = "냉혈"
		L["Riposte"] = ""
		L["Shadowstep"] = ""
		L["Cheating Death"] = ""

		L["Bestial Wrath"] = "야수의 격노"
		L["Intimidation"] = "위협"
		L["Deterrence"] = "공격 저지"
		L["Scatter Shot"] = "산탄 사격"
		L["Aimed Shot"] = "조준 사격"
		L["Silencing Shot"] = ""
		L["Readiness"] = ""

		L["Last Stand"] = "최후의 저항"
		L["Sweeping Strikes"] = "휩쓸기 일격"
		L["Death Wish"] = "죽음의 소원"
		L["Concussion Blow"] = "충격의 일격"

		L["Inner Focus"] = "내면의 집중력"
		L["Power Infusion"] = "마력 주입"
		L["Silence"] = "침묵"
		L["Pain Suppression"] = ""
		L["Lightwell"] = ""

		L["Elemental Mastery"] = "정기의 깨달음"
		L["Stormstrike"] = "폭풍의 일격"
		L["Nature's Swiftness"] = "자연의 신속함"
		L["Shamanistic Rage"] = ""

		L["Fel Domination"] = "마의 지배"
		L["Amplify Curse"] = "저주 증폭"
		L["Shadowfury"] = ""
		L["Backlash"] = ""

		L["Divine Favor"] = "신의 은총"
		L["Holy Shock"] = "신성 충격"
		L["Holy Shield"] = "신성한 방패"
		L["Repentance"] = "참회"
		L["Divine Illumination"] = ""
		L["Avenger's Shield"] = ""
		L["Crusader Strike"] = ""

		L["Innervate"] = "정신 자극"
		L["Feral Charge"] = "야성의 돌진"
		L["Swiftmend"] = "신속한 치유"
		L["Force of Nature"] = ""

		L["Presence of Mind"] = "냉정"
		L["Arcane Power"] = "신비의 마법 강화"
		L["Combustion"] = "발화"
		L["Cold Snap"] = "매서운 한파"
		L["Ice Block"] = "얼음 방패"
		L["Dragon's Breath"] = ""
		L["Icy Veins"] = ""
		L["Summon Water Elemental"] = ""
		L["Freeze"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "포세이큰의 의지"
		L["Perception"] = "직관력"
		L["War Stomp"] = "전투 발구르기"
		L["Stoneform"] = "석화"
		L["Cannibalize"] = "시체먹기"
		L["Blood Fury"] = "피의 격노"
		L["Berserking"] = "광폭화"
		L["Shadowmeld"] = "그림자 숨기"
		L["Escape Artist"] = "탈출의 명수"
		L["Arcane Torrent"] = ""
		L["Mana Tap"] = ""
		L["Gift of the Naaru"] = ""

		L["Brittle Armor"] = "불완전한 갑옷"
		L["Unstable Power"] = "불안정한 마력"
		L["Restless Strength"] = "불안정한 힘"
		L["Ephemeral Power"] = "마력의 힘"
		L["Massive Destruction"] = "잔혹한 파괴"
		L["Arcane Potency"] = "신비한 잠재력"
		L["Energized Shield"] = "보호막 강화"
		L["Brilliant Light"] = "찬란한 빛"
		L["Mar'li's Brain Boost"] = "말리의 사고 촉진"
		L["Burst of Energy"] = "기력 폭발"
		L["Refocus"] = "주의 집중"
		L["Venomous Totem"] = "맹독의 토템"
		L["Mind Quickening"] = "사고 촉진"
		L["Gift of Life"] = "생명의 선물"
		L["Blinding Light"] = "빛의 결속"
		L["Nature Aligned"] = "자연 동화"
		L["Earthstrike"] = "대지의 격동"
		L["Badge of the Swarmguard"] = "전투감시병의 휘장"
		L["Speed"] = "신속"
		L["Immune Root/Snare/Stun"] = "이동 불가/덫/기절 면역"
		L["Immune Fear/Polymorph/Snare"] = "공포/변이/덫 면역"
		L["Immune Charm/Fear/Stun"] = "현혹/공포/기절 면역"
		L["Immune Charm/Fear/Polymorph"] = "현혹/공포/변이 변역"
		L["Immune Fear/Polymorph/Stun"] = "공포/변이/기절 면역"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["PvP Trinket"] = ""
		L["Tremendous Fortitude"] = ""
		L["Talisman of the Horde"] = ""
		L["Talisman of the Alliance"] = ""

		L["Frost Reflector"] = "회전냉각식 냉기 반사기"
		L["Shadow Reflector"] = "초광자 암흑 반사기"
		L["Fire Reflector"] = "극고온 화염 반사기"
		
		L["Healing Potion"] = "치유 물약"
		L["Healing Draught"] = "치유 비약"
		L["Restore Mana"] = "마나 회복"
		L["Free Action"] = "자유 의지"
		L["Living Free Action"] = "자유 행동의 물약"
		L["Invulnerability"] = "무적"
		L["Restoration"] = "복원"
		L["Restore Energy"] = "기력 회복"


		L["Recently Bandaged"] = "붕대 치료"
		L["Iron Grenade"] = "철제 수류탄"
		L["Thorium Grenade"] = "토륨 수류탄"
		L["Goblin Sapper Charge"] = "고블린 공병 폭탄"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		L["Adamantite Grenade"] = ""
		L["Super Sapper Charge"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "도주"
		L["Gnomish Rocket Boots"] = "노움 로켓 장화"
		L["Goblin Rocket Boots"] = "고블린 로켓 장화"
		L["Running Speed"] = "이동 속도 증가"
		L["Gnomish Mind Control Cap"] = "노움 정신 지배 모자"
		L["Reckless Charge"] = "무모한 돌진"
		L["Rocket Boots Engaged"] = ""

		-- Warrior
		L["Charge"] = "돌진"
		L["Mocking Blow"] = "도발의 일격"
		L["Mortal Strike"] = "죽음의 일격"
		L["Overpower"] = "제압"
		L["Retaliation"] = "보복"
		L["Thunder Clap"] = "천둥벼락"
		L["Berserker Rage"] = "광전사의 격노"
		L["Bloodthirst"] = "피의 갈증"
		L["Challenging Shout"] = "도전의 외침"
		L["Intercept"] = "봉쇄"
		L["Intimidating Shout"] = "위협의 외침"
		L["Pummel"] = "자루 공격"
		L["Recklessness"] = "무모한 희생"
		L["Whirlwind"] = "소용돌이"
		L["Bloodrage"] = "피의 분노"
		L["Disarm"] = "무장 해제"
		L["Revenge"] = "복수"
		L["Shield Bash"] = "방패 밀쳐내기"
		L["Shield Block"] = "방패 막기"
		L["Shield Slam"] = "방패 밀쳐내기"
		L["Shield Wall"] = "방패의 벽"
		L["Spell Reflect"] = ""
		L["Intervene"] = ""

		-- Paladin
		L["Consecration"] = "신성화"
		L["Exorcism"] = "퇴마술"
		L["Hammer of Wrath"] = "천벌의 망치"
		L["Holy Wrath"] = "신의 격노"
		L["Lay on Hands"] = "신의 축복"
		L["Turn Undead"] = "언데드 퇴치"
		L["Blessing of Freedom"] = "자유의 축복"
		L["Blessing of Protection"] = "보호의 축복"
		L["Divine Intervention"] = "성스러운 중재"
		L["Divine Protection"] = "신의 가호"
		L["Divine Shield"] = "천상의 보호막"
		L["Hammer of Justice"] = "심판의 망치"
		L["Judgement"] = "심판"
		L["Forbearance"] = "참을성"
		L["Righteous Defense"] = ""
		L["Avenging Wrath"] = ""

		-- Mage
		L["Blink"] = "점멸"
		L["Portal: Darnassus"] = "차원의 문: 다르나서스"
		L["Portal: Ironforge"] = "차원의 문: 아이언포지"
		L["Portal: Orgrimmar"] = "차원의 문: 오그리마"
		L["Portal: Stormwind"] = "차원의 문: 스톰윈드"
		L["Portal: Thunder Bluff"] = "차원의 문: 썬더 블러프"
		L["Portal: Undercity"] = "차원의 문: 언더시티"
		L["Blast Wave"] = "화염 폭풍"
		L["Fire Blast"] = "화염 작열"
		L["Fire Ward"] = "화염계 수호"
		L["Cone of Cold"] = "냉기 돌풍"
		L["Frost Nova"] = "얼음 회오리"
		L["Frost Ward"] = "냉기계 수호"
		L["Ice Barrier"] = "얼음 보호막"
		L["Counterspell"] = "마법 차단"
		L["Evocation"] = "환기"
		L["Invisibility"] = ""
		L["Ritual of Refreshment"] = ""

		-- Rogues
		L["Kidney Shot"] = "급소 가격"
		L["Evasion"] = "회피"
		L["Feint"] = "교란"
		L["Gouge"] = "후려치기"
		L["Kick"] = "발차기"
		L["Sprint"] = "전력 질주"
		L["Blind"] = "실명"
		L["Distract"] = "혼란"
		L["Stealth"] = "은신"
		L["Vanish"] = "소멸"
		L["Cloak of Shadows"] = ""

		-- Shaman
		L["Reincarnation"] = "윤회"
		L["Chain Lightning"] = "연쇄 번개"
		L["Earth Shock"] = "대지 충격"
		L["Earthbind Totem"] = "속박의 토템"
		L["Fire Nova Totem"] = "불꽃 회오리 토템"
		L["Flame Shock"] = "화염 충격"
		L["Frost Shock"] = "냉기 충격"
		L["Stoneclaw Totem"] = "돌발톱 토템"
		L["Astral Recall"] = "영혼의 귀환"
		L["Grounding Totem"] = "마법정화 토템"
		L["Mana Tide Totem"] = "마나 해일 토템"
		L["Bloodlust"] = ""
		L["Heroism"] = ""
		L["Fire Elemental Totem"] = ""
		L["Earth Elemental Totem"] = ""

		-- Hunters
		L["Scare Beast"] = "야수 겁주기"
		L["Tranquilizing Shot"] = "평정의 사격"
		L["Arcane Shot"] = "신비한 사격"
		L["Concussive Shot"] = "충격포"
		L["Distracting Shot"] = "견제 사격"
		L["Flare"] = "섬광"
		L["Multi-Shot"] = "일제 사격"
		L["Rapid Fire"] = "속사"
		L["Volley"] = "연발 사격"
		L["Counterattack"] = "역습"
		L["Disengage"] = "철수"
		L["Explosive Trap"] = "폭발의 덫"
		L["Feign Death"] = "죽은척하기"
		L["Freezing Trap"] = "얼음의 덫"
		L["Frost Trap"] = "냉기의 덫"
		L["Immolation Trap"] = "제물의 덫"
		L["Mongoose Bite"] = "살쾡이의 이빨"
		L["Raptor Strike"] = "랩터의 일격"
		L["Wyvern Sting"] = "비룡 쐐기"
		L["Misdirection"] = ""
		L["Kill Command"] = ""
		L["Snake Trap"] = ""
		L["Thunderstomp"] = ""
		L["Warp"] = ""
		L["Dive"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = "영혼석 부활"
		L["Curse of Doom"] = "파멸의 저주"
		L["Death Coil"] = "죽음의 고리"
		L["Howl of Terror"] = "공포의 울부짖음"
		L["Inferno"] = "불지옥"
		L["Ritual of Doom"] = "파멸의 의식"
		L["Shadow Ward"] = "암흑계 수호"
		L["Conflagrate"] = "점화"
		L["Shadowburn"] = "어둠의 연소"
		L["Soul Fire"] = "영혼의 불꽃"
		L["Devour Magic"] = "마법 삼키기"
		L["Spell Lock"] = "주문 잠금"
		L["Lash of Pain"] = "고통의 채찍"
		L["Soothing Kiss"] = "유혹의 입맞춤"
		L["Cleave"] = ""

		-- Priest
		L["Elune's Grace"] = "엘룬의 은총"
		L["Feedback"] = "역순환"
		L["Power Word: Shield"] = "신의 권능: 보호막"
		L["Desperate Prayer"] = "구원의 기도"
		L["Fear Ward"] = "공포의 수호물"
		L["Devouring Plague"] = "파멸의 역병"
		L["Fade"] = "소실"
		L["Mind Blast"] = "정신 분열"
		L["Psychic Scream"] = "영혼의 절규"
		L["Symbol of Hope"] = ""
		L["Chastise"] = ""
		L["Prayer of Mending"] = ""
		L["Shadowfiend"] = ""
		L["Shadow Word: Death"] = ""
		L["Starshards"] = ""
		L["Consume Magic"] = ""
		
		-- Druid
		L["Barkskin"] = "나무 껍질"
		L["Faerie Fire"] = "요정의 불꽃"
		L["Hurricane"] = "허리케인"
		L["Nature's Grasp"] = "자연의 손아귀"
		L["Bash"] = "강타"
		L["Challenging Roar"] = "도전의 포효"
		L["Cower"] = "웅크리기"
		L["Dash"] = "질주"
		L["Enrage"] = "분노"
		L["Frenzied Regeneration"] = "광포한 재생력"
		L["Prowl"] = "숨기"
		L["Tiger's Fury"] = "맹공격"
		L["Rebirth"] = "환생"
		L["Tranquility"] = "평온"
		
return end

if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	-- Thanks to ming1455 and tanzhijianorg for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "剑刃乱舞"
		L["Adrenaline Rush"] = "冲动"
		L["Preparation"] = "伺机待发"
		L["Ghostly Strike"] = "鬼魅攻击"
		L["Premeditation"] = "预谋"
		L["Cold Blood"] = "冷血"
		L["Riposte"] = "还击"
		L["Shadowstep"] = "暗影步"
		L["Cheating Death"] = "装死"

		L["Bestial Wrath"] = "血性狂暴"
		L["Intimidation"] = "胁迫"
		L["Deterrence"] = "威慑"
		L["Scatter Shot"] = "驱散射击"
		L["Aimed Shot"] = "瞄准射击"
		L["Silencing Shot"] = "沉默射击"
		L["Readiness"] = "准备就绪"

		L["Last Stand"] = "破釜沉舟"
		L["Sweeping Strikes"] = "横扫攻击"
		L["Death Wish"] = "死亡之愿"
		L["Concussion Blow"] = "震荡猛击"

		L["Inner Focus"] = "心灵专注"
		L["Power Infusion"] = "能量灌注"
		L["Silence"] = "沉默"
		L["Pain Suppression"] = "痛苦压制"
		L["Lightwell"] = "光明之泉"

		L["Elemental Mastery"] = "元素掌握"
		L["Stormstrike"] = "风暴打击"
		L["Nature's Swiftness"] = "自然迅捷"
		L["Shamanistic Rage"] = "萨满之怒"

		L["Fel Domination"] = "恶魔支配"
		L["Amplify Curse"] = "诅咒增幅"
		L["Shadowfury"] = "暗影之怒"
		L["Backlash"] = "反冲"

		L["Divine Favor"] = "神恩术"
		L["Holy Shock"] = "神圣震击"
		L["Holy Shield"] = "神圣之盾"
		L["Repentance"] = "忏悔"
		L["Divine Illumination"] = "神启"
		L["Avenger's Shield"] = "复仇者之盾"
		L["Crusader Strike"] = "十字军打击"

		L["Innervate"] = "激活"
		L["Faerie Fire (Feral)"] = "精灵之火（野性）"
		L["Feral Charge"] = "野性冲锋"
		L["Swiftmend"] = "迅捷治愈"
		L["Force of Nature"] = "自然之力"

		L["Presence of Mind"] = "气定神闲"
		L["Arcane Power"] = "奥术强化"
		L["Combustion"] = "燃烧"
		L["Cold Snap"] = "急速冷却"
		L["Ice Block"] = "寒冰屏障"
		L["Dragon's Breath"] = "龙息术"
		L["Icy Veins"] = "冰冷血脉"
		L["Summon Water Elemental"] = "召唤水元素"
		L["Freeze"] = "冰冻术"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "被遗忘者的意志"
		L["Perception"] = "感知"
		L["War Stomp"] = "战争践踏"
		L["Stoneform"] = "石像形态"
		L["Cannibalize"] = "食尸"
		L["Blood Fury"] = "血性狂暴"
		L["Berserking"] = "狂暴"
		L["Shadowmeld"] = "影遁"
		L["Escape Artist"] = "逃命专家"
		L["Arcane Torrent"] = "奥术洪流"
		L["Mana Tap"] = "法力分流"
		L["Gift of the Naaru"] = "纳鲁的赐福"

		L["Brittle Armor"] = "脆弱护甲"
		L["Unstable Power"] = "能量无常"
		L["Restless Strength"] = "充沛之力"
		L["Ephemeral Power"] = "短暂能量护符"
		L["Massive Destruction"] = "大规模杀伤性魔法"
		L["Arcane Potency"] = "奥术潜能"
		L["Energized Shield"] = "能量护盾"
		L["Brilliant Light"] = "辉煌之光"
		L["Mar'li's Brain Boost"] = "玛尔里的思想加速"
		L["Burst of Energy"] = "能量爆发"
		L["Refocus"] = "重新准备"
		L["Venomous Totem"] = "毒性图腾"
		L["Mind Quickening"] = "思维敏捷"
		L["Gift of Life"] = "生命赐福"
		L["Blinding Light"] = "盲目之光"
		L["Nature Aligned"] = "自然之盟"
		L["Earthstrike"] = "大地之击"
		L["Badge of the Swarmguard"] = "虫群卫士徽章"
		L["Speed"] = "速度"
		L["Immune Root/Snare/Stun"] = "免疫定身/缠绕/昏迷"
		L["Immune Fear/Polymorph/Snare"] = "免疫恐惧/变形/缠绕"
		L["Immune Charm/Fear/Stun"] = "免疫魅惑/恐惧/昏迷"
		L["Immune Charm/Fear/Polymorph"] = "免疫魅惑/恐惧/变形"
		L["Immune Fear/Polymorph/Stun"] = "免疫恐惧/变形/昏迷"
		L["Tidal Charm"] = "潮汐咒符"
		L["Diamond Flask"] = "钻石水瓶"
		L["Fearless"] = "无畏"
		L["Net-o-Matic"] = "撒网器"
		L["The Burrower's Shell"] = "穴居虫之壳"
		L["Aura of Protection"] = "物理防护"
		L["The Eye of the Dead"] = "亡者之眼"
		L["Essence of Sapphiron"] = "萨菲隆的精华"
		L["Persistent Shield"] = "持续护盾"
		L["Slayer's Crest"] = "屠龙者的纹章"
		L["Kiss of the Spider"] = "蜘蛛之吻" 
		
		L["PvP Trinket"] = "PvP饰品"
		L["Tremendous Fortitude"] = "超级坚韧"
		L["Talisman of the Horde"] = "部落护符"
		L["Talisman of the Alliance"] = " 联盟护符"

		L["Frost Reflector"] = "冰霜反射器"
		L["Shadow Reflector"] = "暗影反射器"
		L["Fire Reflector"] = "火焰反射器"
		
		L["Healing Potion"] = "治疗药水"
		L["Healing Draught"] = "治疗药膏"
		L["Restore Mana"] = "恢复法力"
		L["Free Action"] = "自由行动"
		L["Living Free Action"] = "活力自由行动"
		L["Invulnerability"] = "无敌"
		L["Restoration"] = "恢复"
		L["Restore Energy"] = "恢复能量"


		L["Recently Bandaged"] = "新近包扎"
		L["Iron Grenade"] = "铁皮手雷"
		L["Thorium Grenade"] = "瑟银手雷"
		L["Goblin Sapper Charge"] = "地精工兵炸药"
		L["Flash Bomb"] = "闪光雷"
		L["Arcane Bomb"] = "奥术炸弹"
		L["Adamantite Grenade"] = "精金手雷"
		L["Super Sapper Charge"] = "超级神风炸药"
		
		L["Sleep"] = "催眠术"
		L["Flee"] = "逃跑"
		L["Gnomish Rocket Boots"] = "侏儒火箭靴"
		L["Goblin Rocket Boots"] = "地精火箭靴"
		L["Running Speed"] = "跑步速度"
		L["Gnomish Mind Control Cap"] = "侏儒洗脑帽"
		L["Reckless Charge"] = "无畏冲锋"
		L["Rocket Boots Engaged"] = "火箭靴启动"

		-- Warrior
		L["Charge"] = "冲锋"
		L["Mocking Blow"] = "惩戒痛击"
		L["Mortal Strike"] = "致死打击"
		L["Overpower"] = "压制"
		L["Retaliation"] = "反击风暴"
		L["Thunder Clap"] = "雷霆一击"
		L["Berserker Rage"] = "狂暴之怒"
		L["Bloodthirst"] = "嗜血"
		L["Challenging Shout"] = "挑战怒吼"
		L["Intercept"] = "拦截"
		L["Intimidating Shout"] = "破胆怒吼"
		L["Pummel"] = "拳击"
		L["Recklessness"] = "鲁莽"
		L["Whirlwind"] = "旋风斩"
		L["Bloodrage"] = "血性狂暴"
		L["Disarm"] = "缴械"
		L["Revenge"] = "复仇"
		L["Shield Bash"] = "盾击"
		L["Shield Block"] = "盾牌格挡"
		L["Shield Slam"] = "盾牌猛击"
		L["Shield Wall"] = "盾墙"
		L["Spell Reflect"] = "法术反射"
		L["Intervene"] = "援护"

		-- Paladin
		L["Consecration"] = "奉献"
		L["Exorcism"] = "驱邪术"
		L["Hammer of Wrath"] = "愤怒之锤"
		L["Holy Wrath"] = "神圣愤怒"
		L["Lay on Hands"] = "圣疗术"
		L["Turn Undead"] = "超度亡灵"
		L["Blessing of Freedom"] = "自由祝福"
		L["Blessing of Protection"] = "保护祝福"
		L["Divine Intervention"] = "神圣干涉"
		L["Divine Protection"] = "圣佑术"
		L["Divine Shield"] = "圣盾术"
		L["Hammer of Justice"] = "制裁之锤"
		L["Judgement"] = "审判"
		L["Forbearance"] = "自律"
		L["Righteous Defense"] = "正义防御"
		L["Avenging Wrath"] = "复仇之怒"

		-- Mage
		L["Blink"] = "闪现术"
		L["Portal: Darnassus"] = "传送门：达纳苏斯"
		L["Portal: Ironforge"] = "传送门：铁炉堡"
		L["Portal: Orgrimmar"] = "传送门：奥格瑞玛"
		L["Portal: Stormwind"] = "传送门：暴风城"
		L["Portal: Thunder Bluff"] = "传送门：雷霆崖"
		L["Portal: Undercity"] = "传送门：幽暗城"
		L["Blast Wave"] = "冲击波"
		L["Fire Blast"] = "火焰冲击"
		L["Fire Ward"] = "防护火焰结界"
		L["Cone of Cold"] = "冰锥术"
		L["Frost Nova"] = "冰霜新星"
		L["Frost Ward"] = "防护冰霜结界"
		L["Ice Barrier"] = "寒冰护体"
		L["Counterspell"] = "法术反制"
		L["Evocation"] = "唤醒"
		L["Invisibility"] = "隐形术"
		L["Ritual of Refreshment"] = "召唤餐桌"

		-- Rogues
		L["Kidney Shot"] = "肾击"
		L["Evasion"] = "闪避"
		L["Feint"] = "佯攻"
		L["Gouge"] = "凿击"
		L["Kick"] = "脚踢"
		L["Sprint"] = "疾跑"
		L["Blind"] = "致盲"
		L["Distract"] = "扰乱"
		L["Stealth"] = "潜行"
		L["Vanish"] = "消失"
		L["Cloak of Shadows"] = "暗影斗篷"

		-- Shaman
		L["Reincarnation"] = "复生"
		L["Chain Lightning"] = "闪电链"
		L["Earth Shock"] = "地震术"
		L["Earthbind Totem"] = "地缚图腾"
		L["Fire Nova Totem"] = "火焰新星图腾"
		L["Flame Shock"] = "烈焰震击"
		L["Frost Shock"] = "冰霜震击"
		L["Stoneclaw Totem"] = "石爪图腾"
		L["Astral Recall"] = "星界传送"
		L["Grounding Totem"] = "根基图腾"
		L["Mana Tide Totem"] = "法力之潮图腾"
		L["Bloodlust"] = "嗜血"
		L["Heroism"] = "英勇"
		L["Fire Elemental Totem"] = "火元素图腾"
		L["Earth Elemental Totem"] = "土元素图腾"

		-- Hunters
		L["Scare Beast"] = "恐吓野兽"
		L["Tranquilizing Shot"] = "宁神射击"
		L["Arcane Shot"] = "奥术射击"
		L["Concussive Shot"] = "震荡射击"
		L["Distracting Shot"] = "扰乱射击"
		L["Flare"] = "照明弹"
		L["Multi-Shot"] = "多重射击"
		L["Rapid Fire"] = "急速射击"
		L["Volley"] = "乱射"
		L["Counterattack"] = "反击"
		L["Disengage"] = "逃脱"
		L["Explosive Trap"] = "爆炸陷阱"
		L["Feign Death"] = "假死"
		L["Frost Trap"] = "冰霜陷阱"
		L["Immolation Trap"] = "献祭陷阱"
		L["Mongoose Bite"] = "猫鼬撕咬"
		L["Raptor Strike"] = "猛禽一击"
		L["Wyvern Sting"] = "翼龙钉刺"
		L["Misdirection"] = "误导"
		L["Kill Command"] = "杀戮命令"
		L["Snake Trap"] = "毒蛇陷阱"
		L["Thunderstomp"] = "雷霆践踏"
		L["Warp"] = "迁跃"
		L["Dive"] = "俯冲"

		-- Warlocks
		L["Soulstone Resurrection"] = "灵魂石复活"
		L["Curse of Doom"] = "厄运诅咒"
		L["Death Coil"] = "死亡缠绕"
		L["Howl of Terror"] = "恐惧嚎叫"
		L["Inferno"] = "地狱火"
		L["Ritual of Doom"] = "末日仪式"
		L["Shadow Ward"] = "防护暗影结界"
		L["Conflagrate"] = "燃烧"
		L["Shadowburn"] = "暗影灼烧"
		L["Soul Fire"] = "灵魂之火"
		L["Devour Magic"] = "吞噬魔法"
		L["Spell Lock"] = "法术封锁"
		L["Lash of Pain"] = "剧痛鞭笞"
		L["Soothing Kiss"] = "安抚之吻"
		L["Cleave"] = "顺劈斩"

		-- Priest
		L["Elune's Grace"] = "艾露恩的赐福"
		L["Feedback"] = "回馈"
		L["Power Word: Shield"] = "真言术：盾"
		L["Desperate Prayer"] = "绝望祷言"
		L["Fear Ward"] = "防护恐惧结界"
		L["Devouring Plague"] = "噬灵瘟疫"
		L["Fade"] = "渐隐术"
		L["Mind Blast"] = "心灵震爆"
		L["Psychic Scream"] = "心灵尖啸"
		L["Symbol of Hope"] = "希望符记"
		L["Chastise"] = "责罚"
		L["Prayer of Mending"] = "愈合祷言"
		L["Shadowfiend"] = "暗影恶魔"
		L["Shadow Word: Death"] = "暗言术：灭"
		L["Starshards"] = "星辰碎片"
		L["Consume Magic"] = "吞噬魔法"
		
		-- Druid
		L["Barkskin"] = "树皮术"
		L["Faerie Fire"] = "精灵之火"
		L["Hurricane"] = "飓风"
		L["Nature's Grasp"] = "自然之握"
		L["Bash"] = "重击"
		L["Challenging Roar"] = "挑战咆哮"
		L["Cower"] = "畏缩"
		L["Dash"] = "急奔"
		L["Enrage"] = "狂怒"
		L["Frenzied Regeneration"] = "狂暴回复"
		L["Prowl"] = "潜伏"
		L["Tiger's Fury"] = "猛虎之怒"
		L["Rebirth"] = "复生"
		L["Tranquility"] = "宁静"
		
return end

if LOCALE == "zhTW" then
	-- Traditional Chinese translations go here
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""
		L["Riposte"] = ""
		L["Shadowstep"] = ""
		L["Cheating Death"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""
		L["Silencing Shot"] = ""
		L["Readiness"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""
		L["Pain Suppression"] = ""
		L["Lightwell"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""
		L["Shamanistic Rage"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""
		L["Shadowfury"] = ""
		L["Backlash"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""
		L["Divine Illumination"] = ""
		L["Avenger's Shield"] = ""
		L["Crusader Strike"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""
		L["Force of Nature"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""
		L["Dragon's Breath"] = ""
		L["Icy Veins"] = ""
		L["Summon Water Elemental"] = ""
		L["Freeze"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""
		L["Arcane Torrent"] = ""
		L["Mana Tap"] = ""
		L["Gift of the Naaru"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["PvP Trinket"] = ""
		L["Tremendous Fortitude"] = ""
		L["Talisman of the Horde"] = ""
		L["Talisman of the Alliance"] = ""

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""

		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		L["Adamantite Grenade"] = ""
		L["Super Sapper Charge"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""
		L["Rocket Boots Engaged"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""
		L["Spell Reflect"] = ""
		L["Intervene"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""
		L["Righteous Defense"] = ""
		L["Avenging Wrath"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""
		L["Invisibility"] = ""
		L["Ritual of Refreshment"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""
		L["Cloak of Shadows"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""
		L["Bloodlust"] = ""
		L["Heroism"] = ""
		L["Fire Elemental Totem"] = ""
		L["Earth Elemental Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""
		L["Misdirection"] = ""
		L["Kill Command"] = ""
		L["Snake Trap"] = ""
		L["Thunderstomp"] = ""
		L["Warp"] = ""
		L["Dive"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""
		L["Cleave"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		L["Symbol of Hope"] = ""
		L["Chastise"] = ""
		L["Prayer of Mending"] = ""
		L["Shadowfiend"] = ""
		L["Shadow Word: Death"] = ""
		L["Starshards"] = ""
		L["Consume Magic"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end